#!/bin/bash
set -o errexit

# Install build deps
apt-get -y -q remove imagemagick
apt-get -y -q install xz-utils ghostscript gsfonts pkg-config autoconf libbz2-dev libjpeg-dev libtiff-dev libfreetype6-dev

PREFIX=/usr/local
WDIR=/tmp/imagemagick
mkdir -p $WDIR

# Build and install libpng
git clone -b v1.6.21 git://git.code.sf.net/p/libpng/code $WDIR/libpng
cd $WDIR/libpng
./autogen.sh
./configure --prefix=$PREFIX
make -j 4 all && make install

# Build and install ImageMagick
wget -O $WDIR/ImageMagick.tar.xz "http://www.imagemagick.org/download/releases/ImageMagick-6.9.6-8.tar.xz"
IMDIR=$WDIR/$(tar tf $WDIR/ImageMagick.tar.xz --wildcards "ImageMagick-*/configure" |cut -d/ -f1)
tar xf $WDIR/ImageMagick.tar.xz -C $WDIR
cd $IMDIR
PKG_CONF_LIBDIR=$PREFIX/lib LDFLAGS=-L$PREFIX/lib CFLAGS=-I$PREFIX/include ./configure \
          --prefix=$PREFIX \
          --enable-static \
          --enable-bounds-checking \
          --enable-hdri \
          --enable-hugepages \
          --with-threads \
          --with-modules \
          --with-quantum-depth=16 \
          --without-magick-plus-plus \
          --with-bzlib \
          --with-zlib \
          --without-autotrace \
          --with-freetype \
          --with-jpeg \
          --without-lcms \
          --with-lzma \
          --with-png \
          --with-tiff
make -j 4 all && make install


cd $HOME
rm -rf $WDIR
ldconfig
